site_name: PSYCHEER's Documentations
site_url: https://psycheer.github.io
theme:
  name: material
  custom_dir: overrides
  copyright: ''
  show_footer: false
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.footer
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: purple

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: deep purple
      accent: purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - toggle-sidebar:
      async: True
      javascript: ./toggle-sidebar.js
      show_navigation_by_default: True
      show_toc_by_default: True
      toggle_button: navigation
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PSYCHEER
    - icon: fontawesome/brands/discord
      link: https://bbb.crafttale.eu

nav:
  - Home: index.md
  - NovaBot:
      - Setting up NovaBot: NovaBot/setup.md
      - Configuration: NovaBot/config.md
      - Addons:
        - List: NovaBot/list.md
        - Installation: NovaBot/addons.md
        - Creation: NovaBot/addonCreation.md